### ISSUE TITLE
May I ask if this project has the requirement. txt file? If not, can anyone provide one?

### ISSUE THREAD

**Issue by newforests** [lioryariv/volsdf#10]
May I ask if this project has the requirement. txt file? If not, can anyone provide one?

**Comment by zhangwenniu** [comment]
[environment.yml](https://github.com/lioryariv/volsdf/blob/main/environment.yml) is all you need, except for release settings (In each line, from the second “=” to end).

**Comment by lioryariv** [comment]
Exactly, thank you @zhangwenniu. Just need to install the environment defined using the yml file.
