### ISSUE TITLE
using multiple image resolution and intrinsics

### ISSUE THREAD

**Issue by maorp** [lioryariv/volsdf#15]
hi, thanks for sharing this cool work! is it possible to configure multiple image resolutions and cam intrinsics? if I change scene_dataset.py to support this will the rest of the training succeed?

**Comment by lioryariv** [comment]
Hi, 
Note that each image you have separate intrinsic and extrinsics parameters, meaning the forward pass of the model can work under different cameras. So just need to change scene_dataset.py as you suggested.
