### ISSUE TITLE
the mesh generated by NeRF in the paper

### ISSUE THREAD

**Issue by ychfut** [lioryariv/volsdf#21]
Great job! Can you share the mesh (.ply format) generated by NeRF for each scene on the DTU dataset？

**Comment by Hmartin1978** [comment]
@ychfut Hi, I have the same question. I trained the DTU dataset by original NeRF method, but I can't get a resonable mesh results like paper. Could you give me some advice, very grateful!!!

**Comment by lioryariv** [comment]
I suggest you to try different level sets for density, in the paper we extracted the level set of density=50, you can also try 100 and so on.
