### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by ThanTT** [lioryariv/volsdf#3]
Hi~Is there a pre-trained mode? And I want to know how long it takes to train a model and your computer configuration.
Hope for your reply.

**Comment by ThanTT** [comment]
By the way, I trained VolSDF on the DTU dataset and evaluated the model using eval.py. However, the process is killed and the evaluation fails. I find more than 100% RAM used and my computer has 128G RAM. How to solve the problem?

**Comment by lioryariv** [comment]
Hi and sorry for the late reply.
It takes around 8 hours to train a model on a single GPU. 
We did not published pre-trained model.
To solve OOM issue you can decrease the grid resolution used for marching cube, or spread/break the grid computation.

**Comment by VitorGuizilini-TRI** [comment]
Hi, would it be possible to share a pre-trained model for any of the evaluations?
