### ISSUE TITLE
LaplaceDensity

### ISSUE THREAD

**Issue by WillKen** [lioryariv/volsdf#4]
Hello! Thank you for sharing this wonderful work
I wonder why the author used ` alpha * (0.5 + 0.5 * sdf.sign() * torch.expm1(-sdf.abs() / beta))` instead of  `psi = torch.where(sdf > 0, exp, 1 - exp)` with ` exp = 0.5 * torch.expm1(-sdf.abs() / beta)`.

**Comment by WillKen** [comment]
Sorry, I mistook torch.expm1() for torch.exp().

**Comment by zhan-xu** [comment]
Hi @WillKen, may I ask you a question? Why the implementation here is torch.expm1? I think from the paper, it should be 1-exp?
I think alpha * (0.5 + 0.5 * sdf.sign() * (- torch.expm1(-sdf.abs() / beta))) is consistent with eq 3, isn't it? Thank you!

**Comment by WillKen** [comment]
The author's code is correct. See eq2, s=-sdf. s<=0 means sdf>=0;

**Comment by zhan-xu** [comment]
Thank you for your reply @WillKen. I noticed that, but I didn't really understand. Now it makes sense to me.
