### ISSUE TITLE
How to reconstruct texture after generating mesh ?  

### ISSUE THREAD

**Issue by Jiakui** [lioryariv/volsdf#5]
Dear author,

How to reconstruct texture after generating mesh ? Can you give me any suggestion?

Thanks!

**Comment by siyangbing** [comment]
+1

**Comment by lioryariv** [comment]
Hi and sorry for the late reply.
In order to generate a colored mesh you need to specify a certain viewing direction, since the color is view-dependent.
Choosing the direction of the position (vertex) to the origin yield reasonable texture, i.e view_dir = -x/||x||.
