### ISSUE TITLE
about training on other datasets

### ISSUE THREAD

**Issue by Ayiing** [lioryariv/volsdf#7]
dear authors:
very nice work!
but when i run the program, i met some "problems".
after loading the dataset, i found that the program will display "face_normals incorrect shape, ignoring!", however, i didn't see where print the sentence in code. so i want to know if i miss something, what is going on when i see "face_normals incorrect shape...".
regards

**Comment by lioryariv** [comment]
Hi and sorry for the late reply.
This is trimesh warning (not an error). You can look up for it online for more information.
I have never saw any effect of this warning on the extracted mesh.
