### ISSUE TITLE
Evaluation on BlendedMVS

### ISSUE THREAD

**Issue by giwel** [lioryariv/volsdf#8]
Dear @lioryariv 

Thank you so much for your work. I have not found how to evaluate VolSDF on BlendedMVS dataset, i.e computing the chamfer distance. The BlendedMVS repo doesn't seem to provide such script.

Would you mind pointing me to the right place? Thanks!

**Comment by jiangsijia9495** [comment]
> Dear @lioryariv
> 
> Thank you so much for your work. I have not found how to evaluate VolSDF on BlendedMVS dataset, i.e computing the chamfer distance. The BlendedMVS repo doesn't seem to provide such script.
> 
> Would you mind pointing me to the right place? Thanks!

Same problem here! Have you figured it out?

**Comment by lioryariv** [comment]
Hi, 
BlendedMVS indeed do not provide an official evaluation code for the dataset (as DTU does).
Moreover, the GT meshes are in different scales. That is why we provided out the relative improvements against NeRF reconstructions. 
Code for chamfer distance can be found in different places, a common example is in [pytorch3D](https://github.com/facebookresearch/pytorch3d)
