### ISSUE TITLE
Model not training, evaluation generate blank, lower resolution is not handled 

### ISSUE THREAD

**Issue by ghasemikasra39** [lioryariv/volsdf#9]
After running your source code, I found these issues:

- Your source code does not handle the cases with lower resolutions. e.g. for DTU dataset, if you lower the resolution to something like `[ 300, 400 ]`, the code will crash and the default resolution `[ 1200, 1600 ]` is hard-coded in the source code. 

- The first issue crashes the code also in the `psnr` computation due to the same reason

- The renderings during evaluation generate blank squares. Here bellow you can see the renderings from scan 114 of the DTU dataset:
<img width="655" alt="Screenshot 2022-09-04 at 18 10 42" src="https://user-images.githubusercontent.com/24314029/188322953-3e38bca2-1a7d-400f-95a7-310cdaaeb54c.png">

- It seems the your model is not training at all! Because the `loss` and the `psnr` value dose not change from the beginning and remains at something like `0.1` and `12` respectively. 
- Your source code will not run without lowering the config. You will immediately get OOM error. 

- Your code generates messages like `face_normals incorrect shape, ignoring!` and `face_normals all zero, ignoring!` all the times. I still don't know what they mean, or if they are the cause of the issues above. 

Some of the issues I mentioned above have been already found by others in other issues. I did not see any response from the authors, so I am writing these here. I am looking forward to the authors response.

**Comment by lioryariv** [comment]
Hi, sorry for the delayed answer. The model should run on a lower resolution. I suggest you to check the cameras correlation (can do so using corresponding points visualization). The intrinsics camera should change according to the resolution and it may that you haven't changed it?
 BlenderMVS dataset has lower resolution than DTU and the model work without any special different in the parameters.
Moreover, not training model can sometimes indicates of issue with the camera parameters.

Regarding the warning about "facr_normals", those are TRIMESH warnings (you can look more regarding their meaning), that don't effect the resulting mesh accuracy if just being ignored.
